### ISSUE TITLE
%player_ping% always is 0

### ISSUE THREAD

**Issue by FabiChan99** [Xitee1/PowerBoard#23] opened 2022-10-26 11:15 UTC
%player_ping% always is 0 unless I reload the plugin.
I use 1.18.1

**Comment by Xitee1** [comment] 2022-10-26 11:27
Does it work in other versions?
How long did you wait? It can take up to 5 minutes after joining the server to display the correct ping.

**Comment by FabiChan99** [comment] 2022-10-26 17:26
Yes, this also happens on other versions and I also let it run for 20 mins. Its always 0

**Comment by FabiChan99** [comment] 2022-10-26 17:30
Also it happens for every player

**Comment by Xitee1** [comment] 2022-10-26 17:30
Just to be sure, you're not on a local server or similar?

**Comment by MrClean1337** [comment] 2022-10-26 17:35
Sometimes it happens too, but as @Xitee1 said "It can take up to 5 minutes after joining the server to display the correct ping".

Got no problems 
![image](https://user-images.githubusercontent.com/58367170/198096750-d883d026-a986-479d-a3f9-3ea4e985113c.png)

**Comment by FabiChan99** [comment] 2022-10-27 08:28
> Just to be sure, you're not on a local server or similar?

No its a Spigot Server thats hosted

**Comment by Xitee1** [comment] 2022-11-02 17:35
Closing this issue because it can't be replicated.
It could be caused by a (wrong) proxy configuration, firewalls or something like that. The cause could be by the server hoster.

**Closed** 2022-11-02 17:36 UTC
Labels: bug
