### ISSUE TITLE
Mixed scoreboards bug

### ISSUE THREAD

**Issue by Hazugg** [Xitee1/PowerBoard#3] opened 2022-02-27 19:25 UTC
The scoreboard shows an error, firstly you can't put a scoreboard for all the general worlds, I had to create a scoreboard for each world, everything is fine while a player is connected but if 2 or more enter the scoreboard it begins to change between mine or the another user, then it shows me mine and quickly switches to the other user

This is how it shows me, it changes every time:

![image](https://user-images.githubusercontent.com/31551514/155896512-7c9bda4f-8b15-402f-ba63-4eff731cfd47.png)

![image](https://user-images.githubusercontent.com/31551514/155896636-7425250c-a9d7-4f1c-a99f-9523517d35e2.png)

any way to solve this? I don't know if it has to do with some configuration but I have seen it and everything is ok, or permission issues or simply the plugin the scoreboard part is failing.

**Comment by Xitee1** [comment] 2022-02-27 20:04
> firstly you can't put a scoreboard for all the general worlds, I had to create a scoreboard for each world
Just add multiple conditions like
```
conditions:
  - 'world:world'
  - 'world:world_nether'
  - 'world:world_the_end'
```

To the main problem:
I got this bug report a lot of times, but could not reproduce it once. I tested it just now again with 3 (offline) accounts and still couldn't reproduce it.
Could you send me your PowerBoard config folder so I can try it with your config?

**Comment by Hazugg** [comment] 2022-02-27 20:13
The main problem would be that the changer changes automatically for me or another user, for example it shows me my scoreboard and automatically the second it shows me another user and so on

I attach the folder:
[PowerBoard.zip](https://github.com/Xitee1/PowerBoard/files/8149375/PowerBoard.zip)

**Comment by Hazugg** [comment] 2022-02-27 20:15
I will try to place the conditions to see if it persists the same with the conditions placed

**Comment by Xitee1** [comment] 2022-02-27 20:19
Are you using the API, because the scoreboard in the config is disabled?
And do you use the newest version? The config looks a bit outdated.

**Comment by Hazugg** [comment] 2022-02-27 20:24
Are you talking about placeholderAPI? If so, if I am using it and how would it be outdated, because if I am using the latest version

**Comment by Hazugg** [comment] 2022-02-27 20:25
What should I put or change in the configuration?

**Comment by Xitee1** [comment] 2022-02-27 20:26
No, I don't mean PAPI. I mean the PowerBoardAPI.

First, you have only one scoreboard (you said that you have a scoreboard for each world), and second you have the scoreboard disabled in your config.yml

**Comment by Hazugg** [comment] 2022-02-27 20:35
o yes sorry it was deactivated and the other markers were removed, but now I have it activated and only with one marker and I placed different conditions as you had indicated but it is displayed in the main world but not in the other worlds, because of that problem I had to place different markers for each world and I had that main problem.

![image](https://user-images.githubusercontent.com/31551514/155898750-b2285bb0-caa0-42a5-901f-88d5813300c2.png)

**Comment by Hazugg** [comment] 2022-02-27 20:35
if I currently have the latest version of the api

**Comment by Xitee1** [comment] 2022-02-27 20:37
What is "recursos" in the condition list? If it is a world, you have to write "world:" in front of it. Otherwise it will not work.

**Comment by Hazugg** [comment] 2022-02-27 20:39
if I have seen it sorry but even with this in the other worlds that I put it didn't work either, it didn't show up, just now I'm fixing it and I'm downloading again the last configuration to rule out that it's that.

**Comment by Hazugg** [comment] 2022-02-27 20:46
The current configuration is loaded, I put the conditions of the worlds, but it still persists, it shows me the scoreboard in the main world when I enter the server, but then I tp or go to another world and it is not shown in any of the list.

![image](https://user-images.githubusercontent.com/31551514/155899204-d0c3fbd7-2442-44d2-85a2-53700be3816b.png)

[PowerBoard.zip](https://github.com/Xitee1/PowerBoard/files/8149411/PowerBoard.zip)

**Comment by Xitee1** [comment] 2022-02-27 20:49
Ok.
Are there any error messages in the console?
If yes, please send me the log.
If not, enable the debug in the config.yml, restart the server and reproduce the problem (join the server and switch the world). Then send me the log.

**Comment by Hazugg** [comment] 2022-02-27 20:59
There is no error message, I just activated the debug, restarted and tested and it still does not appear in the other worlds:

![image](https://user-images.githubusercontent.com/31551514/155899641-27e30a2d-d2fa-4c73-9f3c-3c690c0f5e15.png)

![image](https://user-images.githubusercontent.com/31551514/155899531-aa2a5872-d31b-4365-9bd9-4609ed4dd107.png)

**Comment by Xitee1** [comment] 2022-02-27 21:00
Please tp to another world so I can see what is happening in the console

**Comment by Hazugg** [comment] 2022-02-27 21:04
Nothing happens in the console when I go to another world, only the scoreboard disappears, and I just realized that when I go back to the world where it is shown when I enter, it also disappears.

![image](https://user-images.githubusercontent.com/31551514/155899875-90ceafc8-60a9-480d-b61d-e9cf320e36a5.png)

**Comment by Hazugg** [comment] 2022-02-27 21:06
but when I create a bookmark for each world, if it is displayed! but it ends up happening the error that is displayed from one user and another and is updated every second shows me another bookmark of a different user who is logged in

**Comment by Xitee1** [comment] 2022-02-27 21:06
Ok that is pretty weird and definitively a bug. I will try to fix it in the next few days.

**Comment by Hazugg** [comment] 2022-02-27 21:08
thank you very much, I will be looking forward to it, good plugin only the scoreboard has that problem, thanks again.

**Comment by MrClean1337** [comment] 2022-07-21 11:36
I don't have any of this bugs.

**Comment by Xitee1** [comment] 2022-07-21 19:39
Most users don't have this bug, but for some reason there are some pretty rare cases where this problem occurs. I have also never experienced this bug myself.

**Comment by Xitee1** [comment] 2023-07-23 16:53
Since this bug hasn't been reported again in a long time I hope that it somehow someday got fixed. Closing for now.

**Closed by Xitee1** 2023-07-23 16:53 UTC
Labels: bug, wontfix
